version: '3'

networks:
  diplom-network:
    name: diplom-network
    external: false

services:
  diplom-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4200"
    restart: unless-stopped
